// <auto-generated />
using CourierApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourierApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250312204241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CourierApp.Models.Phenomenon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Phenomenon");
                });

            modelBuilder.Entity("CourierApp.Models.Weather", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AirTemperature")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhenomenonID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WMOCode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WindSpeed")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("PhenomenonID");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("CourierApp.Models.Weather", b =>
                {
                    b.HasOne("CourierApp.Models.Phenomenon", "Phenomenon")
                        .WithMany()
                        .HasForeignKey("PhenomenonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phenomenon");
                });
#pragma warning restore 612, 618
        }
    }
}
